#pts_sylius_article_plugin_article:
#  resource: |
#    alias: pts_sylius_article_plugin.article
#    path: /admin/article
#    templates: SyliusAdminBundle:Crud
#    permission: true
#    grid: pts_sylius_article_plugin_article
#    vars:
#        index:
#            subheader: app.filters.subheader
#            icon: filter
#  type: sylius.resource