pts_sylius_article_plugin:
  driver: doctrine/orm
#  resources:
#    article:
#      classes:
#        model: PTS\SyliusArticlePlugin\Entity\Article
#        form: PTS\SyliusArticlePlugin\Form\Type\ArticleType
#    category:
#      classes:
#        model: PTS\SyliusArticlePlugin\Entity\Category

sylius_taxonomy:
  resources:
    taxon:
      classes:
        controller: PTS\SyliusArticlePlugin\Controller\TaxonController
