services:
#
#  pts_sylius_blog_plugin.form.type.article:
#    class: PTS\SyliusBlogPlugin\Form\Type\ArticleType
#    arguments: ['%pts_sylius_blog_plugin.model.article.class%', ["Default"]]
#    tags:
#      - { name: form.type }
#
#  pts_sylius_blog_plugin.form.type.category:
#    class: PTS\SyliusBlogPlugin\Form\Type\CategoryType
#    arguments: ['%pts_sylius_blog_plugin.model.category.class%', ["Default"]]
#    tags:
#      - { name: form.type }
